# This file was generated by GoReleaser. DO NOT EDIT.
cask "cospace" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "03693175120fd4a1edc21a49d3fd5632b10cd81ff089c445fa2e930e7770ae3f"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4252b90fd116f403e60ae626fb76db614f999e61a2487d68215f557bd8aef7a2"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b701f662ac85503c8cdb1fb850ede3388cef3b26f2856890fccd26843d8aee46"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "196b995e74d642aff1c432a5671c16bdf743e27f7e2112d8fe3800c465c7814e"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_linux_amd64.tar.gz"
    end
  end

  name "cospace"
  desc "Join a shared AI dev space over plain ssh — the CoSpace guest tool."
  homepage "https://github.com/JingxuanKang/cospace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cospace"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cospace"
    end
  end

  # No zap stanza required
end
