# This file was generated by GoReleaser. DO NOT EDIT.
cask "cospace" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "fe48eac0054aadbd776616cb9b05e0715b003b5c17d02b38d12fd9dbec7ed7fb"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "50613482173772471e67908f90f8bfb18c58e399c6f27e75fc86bbaf71c63db5"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e959dddd12bc2145565a943dcfb3c3336223498ac5705a1de1762802c917d5cb"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "98eb7816bfa5d63f45021e14c24b984e90b03ec880034c5487e5e63a48245a90"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_linux_amd64.tar.gz"
    end
  end

  name "cospace"
  desc "Join a shared AI dev space over plain ssh — the CoSpace guest tool."
  homepage "https://github.com/JingxuanKang/cospace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cospace"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cospace"
    end
  end

  # No zap stanza required
end
