# This file was generated by GoReleaser. DO NOT EDIT.
cask "cospace" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "929391c353b69fa3271c2decbfd650b1618730128daaef1e19b2435df46c6678"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fff19eca82e4460ab9dc6d4487df331182c9f90af9c75470c66fab61c679fe6b"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8a844df82c9a9f6156c776141229204336dcbee9fcd91124c16374175067be9f"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "31000f14e30fcbc002e6c9fc7fe904aaecb303471b1b23dfc3273455eaf89170"
      url "https://github.com/JingxuanKang/cospace/releases/download/v#{version}/cospace_linux_amd64.tar.gz"
    end
  end

  name "cospace"
  desc "Join a shared AI dev space over plain ssh — the CoSpace guest tool."
  homepage "https://github.com/JingxuanKang/cospace"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cospace"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/cospace"
    end
  end

  # No zap stanza required
end
